services:
  app:
    image: ghcr.io/jayrinaldime/open-subtitles:latest
    environment:
      - GROQ_API_KEY=your_groq_api_key_here
      - TRANSCRIPTION_PROVIDER=groq
      - TRANSLATION_PROVIDER=groq
      - LLM_STT_MODEL=whisper-large-v3
      - LLM_CHAT_MODEL=llama-3.2-3b-preview
      - LOG_LEVEL=ERROR
    ports:
      - "8000:8000"