version: '3.8'

services:
  app:
    image: ghcr.io/jayrinaldime/open-subtitles:latest
    environment:
      - OLLAMA_HOST=http://<HOST IP ADDRESS HERE>:11434
      - TRANSCRIPTION_PROVIDER=local
      - TRANSLATION_PROVIDER=ollama
      - LLM_CHAT_MODEL=llama2
      - SYSTEM_PROMPT_TRANSLATE=You are a helpful translator. Translate the text to the {LANGUAGE} language and only return the translated text. Do **not** state the original input and do **NOT** summarize!
      - LOCAL_TRANSCRIPTION_ENDPOINT=http://whisper-gpu:9000/asr
    ports:
      - "8000:8000"
    depends_on:
      - whisper-gpu

  # FOR GPU Speech to Text processing
  whisper-gpu:
    image: onerahmet/openai-whisper-asr-webservice
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - ASR_MODEL=base
    #ports:
    #  - "9000:9000"
    volumes:
      - cache-whisper:/root/.cache/whisper

 # FOR CPU Speech to Text processing
  # whisper-cpu:
  #   image: onerahmet/openai-whisper-asr-webservice
  #   environment:
  #     - ASR_MODEL=base
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - cache-whisper:/root/.cache/whisper