version: '3.8'

services:
  app:
    image: ghcr.io/jayrinaldime/open-subtitles:latest
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
      - GROQ_API_KEY=your_groq_api_key_here
      - TRANSCRIPTION_PROVIDER=groq
      - TRANSLATION_PROVIDER=groq
      - LOG_LEVEL=INFO
      - MAX_RETRIES=3
      - API_TIMEOUT=30
      - API_BASE_URL=https://api.groq.com
      - LLM_STT_MODEL=whisper-large-v3
      - LLM_CHAT_MODEL=llama-3.2-3b-preview
      - SYSTEM_PROMPT_TRANSLATE=You are a helpful translator. Translate the text to the {LANGUAGE} language and only return the translated text. Do **not** state the original input and do **NOT** summarize!
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - groq

  groq:
    image: groq/groq:latest
    environment:
      - GROQ_API_KEY=your_groq_api_key_here
    ports:
      - "8080:8080"
