services:
  app:
    image: ghcr.io/jayrinaldime/open-subtitles:latest
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
      - TRANSCRIPTION_PROVIDER=openai
      - TRANSLATION_PROVIDER=openai
      - LLM_STT_MODEL=whisper-1
      - LLM_CHAT_MODEL=gpt-3.5-turbo
      - LOG_LEVEL=ERROR
    ports:
      - "8000:8000"
    
